"""PRISM Research Benchmarking, Evidence Synthesis & Reporting Subsystem."""

from __future__ import annotations

from prism.benchmarking.adapters import (
    adapt_any_report,
    adapt_architecture_comparison_report,
    adapt_explainability_report,
    adapt_multimodal_report,
    adapt_reconstruction_report,
    adapt_representation_geometry_report,
    adapt_robustness_report,
    adapt_spatial_transfer_report,
    adapt_ssl_report,
    adapt_temporal_report,
    adapt_transfer_report,
    adapt_uncertainty_report,
)
from prism.benchmarking.aggregation import (
    aggregate_repeated_seeds,
    group_and_aggregate,
)
from prism.benchmarking.comparisons import (
    audit_comparison_control,
    compute_pairwise_comparison,
)
from prism.benchmarking.contracts import (
    AggregatedBenchmarkResult,
    BenchmarkCampaign,
    BenchmarkMatrix,
    BenchmarkResultCell,
    BenchmarkTable,
    ComparisonControlAudit,
    EvidenceGap,
    FigureSpecification,
    MetricDefinition,
    MissingExperimentPlan,
    PairwiseComparisonResult,
    ParetoAnalysisResult,
    PRISMResearchReport,
    RepresentationProfile,
    ReproducibilityManifest,
    ResearchFinding,
    ResearchQuestion,
    ResearchReportSpecification,
    compute_campaign_fingerprint,
)
from prism.benchmarking.enums import (
    CampaignStatus,
    ChartType,
    ComparisonControlStatus,
    EvidenceStrength,
    FactorID,
    MetricCategory,
    MetricDirection,
    ResultStatus,
)
from prism.benchmarking.matrices import (
    build_benchmark_matrix,
    build_benchmark_table,
)
from prism.benchmarking.registry import (
    FactorRegistry,
    MetricRegistry,
    canonical_metric_registry,
)
from prism.benchmarking.store import BenchmarkResultStore

__all__ = [
    "AggregatedBenchmarkResult",
    "BenchmarkCampaign",
    "BenchmarkMatrix",
    "BenchmarkResultCell",
    "BenchmarkResultStore",
    "BenchmarkTable",
    "CampaignStatus",
    "ChartType",
    "ComparisonControlAudit",
    "ComparisonControlStatus",
    "EvidenceGap",
    "EvidenceStrength",
    "FactorID",
    "FactorRegistry",
    "FigureSpecification",
    "MetricCategory",
    "MetricDefinition",
    "MetricDirection",
    "MetricRegistry",
    "MissingExperimentPlan",
    "PRISMResearchReport",
    "PairwiseComparisonResult",
    "ParetoAnalysisResult",
    "RepresentationProfile",
    "ReproducibilityManifest",
    "ResearchFinding",
    "ResearchQuestion",
    "ResearchReportSpecification",
    "ResultStatus",
    "adapt_any_report",
    "adapt_architecture_comparison_report",
    "adapt_explainability_report",
    "adapt_multimodal_report",
    "adapt_reconstruction_report",
    "adapt_representation_geometry_report",
    "adapt_robustness_report",
    "adapt_spatial_transfer_report",
    "adapt_ssl_report",
    "adapt_temporal_report",
    "adapt_transfer_report",
    "adapt_uncertainty_report",
    "aggregate_repeated_seeds",
    "audit_comparison_control",
    "build_benchmark_matrix",
    "build_benchmark_table",
    "canonical_metric_registry",
    "compute_campaign_fingerprint",
    "compute_pairwise_comparison",
    "group_and_aggregate",
]
