"""Uncertainty, calibration, and OOD analysis domain package."""

from __future__ import annotations

from prism.uncertainty.calibration import (
    compute_brier_score,
    compute_calibration_report,
    compute_confidence_subset_summary,
    compute_expected_calibration_error,
    compute_maximum_calibration_error,
    compute_negative_log_likelihood,
    compute_reliability_bins,
)
from prism.uncertainty.contracts import (
    CalibrationReport,
    CalibrationSample,
    ClassCalibrationSummary,
    ConfidenceSubsetSummary,
    CorruptionUncertaintyCurve,
    OODBinaryEvaluationSummary,
    OODReferenceSet,
    OODSample,
    OODScoreResult,
    PredictionFlipUncertainty,
    PredictiveDistribution,
    ReliabilityBin,
    RepresentationConfidenceRelationship,
    TemperatureScalingResult,
    UncertaintyAnalysisReport,
)
from prism.uncertainty.enums import (
    BinningStrategy,
    CalibrationMode,
    ConfidenceMetric,
    OODCategory,
    OODScoreMethod,
    ThresholdPolicy,
    UncertaintyFailureType,
)
from prism.uncertainty.metrics import (
    compute_aupr,
    compute_auroc,
    evaluate_ood_binary_classification,
    select_ood_threshold,
)
from prism.uncertainty.ood_scores import (
    compute_class_centroid_ood_score,
    compute_energy_ood_score,
    compute_entropy_ood_score,
    compute_knn_ood_score,
    compute_max_softmax_ood_score,
    score_ood_sample,
)
from prism.uncertainty.probabilities import (
    batch_predictive_distributions,
    compute_logit_margin,
    compute_normalized_entropy,
    compute_predictive_distribution,
    compute_predictive_entropy,
    compute_probability_margin,
    compute_stable_softmax,
)
from prism.uncertainty.temperature import (
    apply_temperature_scaling,
    evaluate_calibrated_predictions,
    fit_temperature_scaling,
)

__all__ = [
    "BinningStrategy",
    "CalibrationMode",
    "CalibrationReport",
    "CalibrationSample",
    "ClassCalibrationSummary",
    "ConfidenceMetric",
    "ConfidenceSubsetSummary",
    "CorruptionUncertaintyCurve",
    "OODBinaryEvaluationSummary",
    "OODCategory",
    "OODReferenceSet",
    "OODSample",
    "OODScoreMethod",
    "OODScoreResult",
    "PredictionFlipUncertainty",
    "PredictiveDistribution",
    "ReliabilityBin",
    "RepresentationConfidenceRelationship",
    "TemperatureScalingResult",
    "ThresholdPolicy",
    "UncertaintyAnalysisReport",
    "UncertaintyFailureType",
    "apply_temperature_scaling",
    "batch_predictive_distributions",
    "compute_aupr",
    "compute_auroc",
    "compute_brier_score",
    "compute_calibration_report",
    "compute_class_centroid_ood_score",
    "compute_confidence_subset_summary",
    "compute_energy_ood_score",
    "compute_entropy_ood_score",
    "compute_expected_calibration_error",
    "compute_knn_ood_score",
    "compute_logit_margin",
    "compute_max_softmax_ood_score",
    "compute_maximum_calibration_error",
    "compute_negative_log_likelihood",
    "compute_normalized_entropy",
    "compute_predictive_distribution",
    "compute_predictive_entropy",
    "compute_probability_margin",
    "compute_reliability_bins",
    "compute_stable_softmax",
    "evaluate_calibrated_predictions",
    "evaluate_ood_binary_classification",
    "fit_temperature_scaling",
    "score_ood_sample",
    "select_ood_threshold",
]
