"""Unit tests for PreparedExecution / RuntimeContext."""

import pytest

from prism.core.metadata import (
    CodeRevisionMetadata,
    EnvironmentMetadata,
    HardwareMetadata,
)
from prism.experiments.context import PreparedExecution
from prism.experiments.reproducibility import ReproducibilityConfiguration
from prism.experiments.seeding import SeedInitializationResult


@pytest.fixture
def sample_prepared_execution() -> PreparedExecution:
    repro = ReproducibilityConfiguration(seed=42, deterministic=True)
    seeding = SeedInitializationResult(
        requested_seed=42,
        deterministic_requested=True,
        python_seeded=True,
        configured_backends=["python"],
    )
    hardware = HardwareMetadata(
        cpu_count=8,
        cpu_architecture="arm64",
        compute_backend="cpu",
    )
    env = EnvironmentMetadata(
        python_version="3.11.0",
        os="macOS 14.5",
        hardware="8 CPU cores, arm64, CPU Backend",
        hardware_info=hardware,
        packages={"prism": "0.1.0"},
    )
    code_rev = CodeRevisionMetadata(
        git_commit="a" * 40,
        short_commit="aaaaaaa",
        git_branch="main",
        is_dirty=False,
    )
    return PreparedExecution(
        experiment_id="exp-cifar10-resnet18",
        run_id="run-exp01-trial01",
        configuration_fingerprint="b" * 64,
        reproducibility=repro,
        seeding_result=seeding,
        environment=env,
        hardware=hardware,
        code_revision=code_rev,
        warnings=["Test warning"],
    )


@pytest.mark.unit
def test_prepared_execution_structure(
    sample_prepared_execution: PreparedExecution,
) -> None:
    """Verify attributes of PreparedExecution."""
    assert sample_prepared_execution.experiment_id == "exp-cifar10-resnet18"
    assert sample_prepared_execution.run_id == "run-exp01-trial01"
    assert sample_prepared_execution.reproducibility.seed == 42
    assert sample_prepared_execution.seeding_result.python_seeded is True
    assert sample_prepared_execution.hardware.cpu_count == 8


@pytest.mark.unit
def test_prepared_execution_reproducibility_report(
    sample_prepared_execution: PreparedExecution,
) -> None:
    """Verify structured capability report generated by PreparedExecution."""
    report = sample_prepared_execution.get_reproducibility_report()

    assert report["experiment_id"] == "exp-cifar10-resnet18"
    assert report["run_id"] == "run-exp01-trial01"
    assert report["requested"]["seed"] == 42
    assert report["configured"]["seeded_backends"] == ["python"]
    assert report["provenance"]["git_commit"] == "a" * 40
    assert report["warnings"] == ["Test warning"]


@pytest.mark.unit
def test_prepared_execution_serialization_round_trip(
    sample_prepared_execution: PreparedExecution,
) -> None:
    """Verify JSON and dict serialization and deserialization."""
    # Dict round trip
    dumped_dict = sample_prepared_execution.to_dict()
    restored_dict = PreparedExecution.from_dict(dumped_dict)
    assert restored_dict.experiment_id == sample_prepared_execution.experiment_id
    assert (
        restored_dict.configuration_fingerprint
        == sample_prepared_execution.configuration_fingerprint
    )
    assert (
        restored_dict.hardware.cpu_architecture
        == sample_prepared_execution.hardware.cpu_architecture
    )

    # JSON round trip
    json_str = sample_prepared_execution.to_json()
    restored_json = PreparedExecution.from_json(json_str)
    assert restored_json.run_id == sample_prepared_execution.run_id
    assert (
        restored_json.code_revision.git_commit
        == sample_prepared_execution.code_revision.git_commit
    )
